// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
	onboarding: {
		eyebrow: "Fitness Training Platform";
		title: "Kom in contact met trainers en train slimmer";
		subtitle: "Vind gecertificeerde trainers, ontvang gepersonaliseerde trainingsschema's en houd samen uw voortgang bij.";
		features: {
			findTrainer: {
				title: "Vind jouw trainer";
				description: "Kom in contact met gecertificeerde personal trainers die aansluiten bij uw fitnessdoelen.";
			};
			personalWorkouts: {
				title: "Krijg snel trainingen";
				description: "Ontvang aangepaste trainingsschema's rechtstreeks van uw trainer.";
			};
			shareProgress: {
				title: "Deel je voortgang";
				description: "Deel je voortgang in realtime met je trainer en ontvang direct feedback.";
			};
			track: {
				title: "Volg je voortgang";
				description: "Bekijk je geschiedenis en statistieken om je voortgang in de tijd bij te houden.";
			};
		};
		continue: "Doorgaan";
		footer: "Maak een account aan om trainers te vinden, gepersonaliseerde trainingen te ontvangen en uw fitnesstraject bij te houden.";
	};
	signIn: {
		title: "Meld je aan bij {title}";
		subtitle: "Meld je aan bij je account om door te gaan naar {title}";
		divider: "of";
		email: "E-mail";
		password: "Wachtwoord";
		remember: "Onthoud mij";
		forgot: "Wachtwoord vergeten?";
		button: "Inloggen";
		continue: "Doorgaan met {provider}";
		noAccount: "Nog geen account?";
		linkText: "Registreren";
		tos: "Door je in te loggen, ga je akkoord met onze <tos>Servicevoorwaarden</tos> en <privacy>Privacybeleid</privacy>.";
	};
	signUp: {
		title: "Registreren voor {title}";
		subtitle: "Maak een account aan om door te gaan naar {title}";
		divider: "of";
		username: "Gebruikersnaam";
		email: "E-mailadres";
		button: "Registreren";
		continue: "Doorgaan";
		continueWith: "Doorgaan met {provider}";
		back: "Terug";
		haveAccount: "Heb je al een account?";
		linkText: "Inloggen";
		tos: "Door je aan te melden, ga je akkoord met onze <tos>Servicevoorwaarden</tos> en <privacy>Privacybeleid</privacy>.";
		steps: {
			currentStep: "Stap {current, number} van {total, number}";
			stepOne: {
				title: "Accountgegevens";
				subtitle: "Start met je inloggegevens.";
				inputs: {
					email: {
						label: "E-mailadres";
						placeholder: "Voer je e-mailadres in";
					};
					password: {
						label: "Wachtwoord";
						placeholder: "Voer je wachtwoord in";
					};
					confirmPassword: {
						label: "Bevestig wachtwoord";
						placeholder: "Bevestig je wachtwoord";
					};
				};
			};
			stepTwo: {
				title: "Persoonlijke gegevens";
				subtitle: "Vertel ons wie je bent.";
				inputs: {
					firstname: {
						label: "Voornaam";
						placeholder: "Voer je voornaam in";
					};
					lastname: {
						label: "Achternaam";
						placeholder: "Voer je achternaam in";
					};
					username: {
						label: "Gebruikersnaam";
						placeholder: "Kies een gebruikersnaam";
					};
				};
			};
			stepThree: {
				title: "Trainingsniveau";
				subtitle: "Vertel ons je ervaring zodat we je training kunnen afstemmen.";
				inputs: {
					experienceLevel: {
						label: "Ervaringsniveau";
						description: "We stemmen aanbevolen trainingen en intensiteit af op dit niveau.";
						options: {
							beginner: {
								label: "Beginner";
								description: "Nieuw in fitness of net begonnen.";
							};
							intermediate: {
								label: "Gemiddeld";
								description: "Redelijk ervaren, op zoek naar verbetering.";
							};
							advanced: {
								label: "Geavanceerd";
								description: "Ervaren, gericht op piekprestaties.";
							};
							professional: {
								label: "Professioneel";
								description: "Zeer ervaren, trainend op een concurrentie niveau.";
							};
						};
					};
				};
			};
			stepFour: {
				title: "Over jou";
				subtitle: "Voeg een korte bio en je belangrijkste fitnessdoelen toe.";
				inputs: {
					bio: {
						label: "Bio";
						description: "Een korte bio helpt bij gepersonaliseerde aanbevelingen.";
						placeholder: "Vertel ons iets over jezelf";
					};
					goals: {
						label: "Doelen";
						description: "Vertel je belangrijkste fitnessdoelen.";
						placeholder: "Wat zijn je fitnessdoelen?";
					};
				};
			};
		};
		confirmPassword: "Bevestig wachtwoord";
		password: "Wachtwoord";
	};
	profile: {
		title: {
			label: "Profiel";
			loading: "Bezig met laden...";
			failed: "Profiel laden mislukt";
		};
		rows: {
			email: {
				label: "E-mail";
			};
			role: {
				label: "Rol";
			};
			experience: {
				label: "Ervaring";
				options: {
					beginner: "Beginner";
					intermediate: "Gemiddeld";
					advanced: "Geavanceerd";
					professional: "Professioneel";
				};
			};
			goals: {
				label: "Doelen";
				empty: "Nog geen doelen ingesteld";
			};
			bio: {
				label: "Bio";
				empty: "Nog geen bio ingesteld";
			};
		};
		tryAgain: "Probeer het later opnieuw.";
		actions: {
			retry: "Opnieuw";
			signOut: "Afmelden";
			editProfile: "Profiel bewerken";
		};
		editModal: {
			title: "Profiel bewerken";
			inputs: {
				firstName: {
					label: "Voornaam";
					placeholder: "Voer je voornaam in";
				};
				lastName: {
					label: "Achternaam";
					placeholder: "Voer je achternaam in";
				};
				bio: {
					label: "Bio";
					description: "Een korte bio helpt bij gepersonaliseerde aanbevelingen.";
					placeholder: "Vertel ons iets over jezelf";
				};
				goals: {
					label: "Doelen";
					description: "Vertel je belangrijkste fitnessdoelen.";
					placeholder: "Wat zijn je fitnessdoelen?";
				};
				experienceLevel: {
					label: "Ervaringsniveau";
					description: "We stemmen aanbevolen trainingen en intensiteit af op dit niveau.";
					options: {
						beginner: {
							label: "Beginner";
							description: "Nieuw in fitness of net begonnen.";
						};
						intermediate: {
							label: "Gemiddeld";
							description: "Redelijk ervaren, op zoek naar verbetering.";
						};
						advanced: {
							label: "Geavanceerd";
							description: "Ervaren, gericht op piekprestaties.";
						};
						professional: {
							label: "Professioneel";
							description: "Zeer ervaren, trainend op een concurrentie niveau.";
						};
					};
				};
			};
			buttons: {
				save: "Wijzigingen opslaan";
				saving: "Bezig met opslaan...";
				cancel: "Annuleren";
			};
			messages: {
				success: "Profiel succesvol bijgewerkt!";
				error: "Fout bij het bijwerken van het profiel.";
			};
		};
	};
	trainingPrograms: {
		header: {
			title: "Trainingsprogramma's";
			available: "{count, plural, =0 {Geen programma's} =1 {Een programma} other {# programma's}} beschikbaar";
			indicators: {
				loading: "Programma's laden";
				refreshing: "Programma's verversen";
				none: "Geen programma's beschikbaar";
			};
			badge: {
				loading: "Laden";
				refreshing: "Verversen";
				updated: "Bijgewerkt";
			};
		};
		states: {
			empty: {
				title: "Geen trainingsprogramma's";
				description: "Je hebt nog geen trainingsprogramma's. \nAls een trainer een programma heeft toegewezen, verschijnt dit hier; \nmaak anders uw eerste programma om aan de slag te gaan.";
				refresh: "Ververs";
			};
			error: {
				title: "Trainingsprogramma's niet beschikbaar";
				description: "Kan trainingsprogramma's niet laden. \nControleer uw verbinding en probeer het opnieuw.";
				tryAgain: "Opnieuw proberen";
			};
		};
	};
};
export default messages;
