// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
	"onboarding": {
		eyebrow: "Fitness App";
		title: "Volg je training zonder gedoe";
		subtitle: "Bekijk je voortgang, houd workouts overzichtelijk en meld je pas aan wanneer je klaar bent om alles te synchroniseren.";
		features: {
			progress: {
				title: "Zie je voortgang";
				description: "Houd elke training bij en zie duidelijk hoeveel je al hebt bereikt.";
			};
			fast: {
				title: "Snel loggen";
				description: "Open de app direct en begin zonder lange onboarding.";
			};
			sync: {
				title: "Altijd synchroon";
				description: "Gebruik je account om je trainingsgegevens overal beschikbaar te houden.";
			};
		};
		continue: "Verder";
		footer: "Hierna meld je je aan. Je hebt nog geen account nodig om deze eerste pagina te zien.";
	};
	"sign-in": {
		title: "Meld je aan bij {title}";
		subtitle: "Meld je aan bij je account om door te gaan naar {title}";
		divider: "of";
		email: "E-mail";
		password: "Wachtwoord";
		remember: "Onthoud mij";
		forgot: "Wachtwoord vergeten?";
		button: "Inloggen";
		continue: "Doorgaan met {provider}";
		"no-account": "Nog geen account?";
		linkText: "Registreren";
		tos: "Door je in te loggen, ga je akkoord met onze <tos>Servicevoorwaarden</tos> en <privacy>Privacy Policy</privacy>.";
	};
	"sign-up": {
		title: "Registreren voor {title}";
		subtitle: "Maak een account aan om door te gaan naar {title}";
		divider: "of";
		username: "Gebruikersnaam";
		email: "E-mailadres";
		password: "Wachtwoord";
		confirmPassword: "Bevestig wachtwoord";
		button: "Registreren";
		continue: "Doorgaan met {provider}";
		"have-account": "Heb je al een account?";
		linkText: "Inloggen";
		tos: "Door je aan te melden, ga je akkoord met onze <tos>Terms of Service</tos> en <privacy>Privacy Policy</privacy>.";
		name: "Naam";
	};
};
export default messages;
